DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS STORIES;
DROP TABLE IF EXISTS VOTES;
DROP TABLE IF EXISTS BOARDS;
DROP TABLE IF EXISTS BOARDS_USERS;

CREATE TABLE IF NOT EXISTS USERS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  USERNAME VARCHAR(50) UNIQUE NOT NULL,
  EMAIL    VARCHAR(50) UNIQUE NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOARDS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  ADMIN_ID BIGINT NOT NULL CONSTRAINT boards_users_id_fk REFERENCES users
);

CREATE TABLE IF NOT EXISTS STORIES
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  ESTIMATION SMALLINT,
  START_TIME TIMESTAMP NOT NULL,
  FINISH_TIME TIMESTAMP,
  BOARD_ID BIGINT NOT NULL CONSTRAINT boards_stories_id_fk REFERENCES BOARDS
);

CREATE TABLE IF NOT EXISTS VOTES
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  STORY_ID BIGINT NOT NULL CONSTRAINT votes_stories_id_fk REFERENCES STORIES,
  USER_ID BIGINT CONSTRAINT votes_user_id_fk REFERENCES users,
  ROUND SMALLINT NOT NULL,
  ESTIMATION SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS BOARDS_USERS
(
  USER_ID BIGINT NOT NULL CONSTRAINT boards_users_users_id_fk REFERENCES USERS,
  BOARD_ID BIGINT NOT NULL CONSTRAINT boards_users_boards_id_fk REFERENCES BOARDS
);

