DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS STORIES;
DROP TABLE IF EXISTS VOTES;
DROP TABLE IF EXISTS BOARDS;
DROP TABLE IF EXISTS USERS_VOTES;
DROP TABLE IF EXISTS BOARDS_USERS;
DROP TABLE IF EXISTS ESTIMATE_STORIES;

CREATE TABLE IF NOT EXISTS USERS
(
  ID BIGINT PRIMARY KEY NOT NULL,
  USERNAME VARCHAR(50) UNIQUE NOT NULL,
  EMAIL    VARCHAR(50) UNIQUE NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOARDS
(
  ID BIGINT PRIMARY KEY NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  ADMIN_ID BIGINT NOT NULL CONSTRAINT boards_users_id_fk REFERENCES users
);

CREATE TABLE IF NOT EXISTS STORIES
(
  ID BIGINT PRIMARY KEY NOT NULL,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  BOARD_ID BIGINT NOT NULL CONSTRAINT boards_stories_id_fk REFERENCES BOARDS,
  START_TIME  TIMESTAMP NOT NULL,
  FINISH_TIME TIMESTAMP,
  ESTIMATION SMALLINT
);

CREATE TABLE IF NOT EXISTS VOTES
(
  ID BIGINT PRIMARY KEY NOT NULL,
  STORY_ID BIGINT NOT NULL CONSTRAINT votes_stories_id_fk REFERENCES STORIES,
  USER_ID BIGINT NOT NULL CONSTRAINT votes_users_id_fk REFERENCES USERS,
  ROUND SMALLINT NOT NULL,
  ESTIMATION SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS BOARDS_USERS
(
  USER_ID BIGINT NOT NULL CONSTRAINT boards_users_users_id_fk REFERENCES USERS,
  BOARD_ID BIGINT NOT NULL CONSTRAINT boards_users_boards_id_fk REFERENCES BOARDS
);

CREATE SEQUENCE IF NOT EXISTS boards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS stories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE boards ALTER COLUMN id SET DEFAULT boards_id_seq.nextval;
ALTER TABLE stories ALTER COLUMN id SET DEFAULT stories_id_seq.nextval;
ALTER TABLE users ALTER COLUMN id SET DEFAULT users_id_seq.nextval;
ALTER TABLE votes ALTER COLUMN id SET DEFAULT votes_id_seq.nextval;